### ISSUE TITLE
Typings for typescript

### ISSUE THREAD

**Issue by shiro** [klimashkin/css-modules-theme#2]
Typescript is often used with react and provides strong type checks at compile-time.

At the moment there are no typings for `css-modules-theme`.
Perhaps someone with more TS experience could work on this as I'm not used to it yet.

**edit**
I've tried to write some typings for this, although as it seems this completely destroys type safety, since it's impossible to determine the type of the `theme` props as it depends on the `themePrefix` prop.

At this time it is impossible to augment string literal types in TS (Microsoft/TypeScript#12754).

**Comment by klimashkin** [comment]
Version 2.0.0 has been rewritten using TypeScript
